# Generated by Django 4.2 on 2023-04-15 07:54

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import submissions.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('compile_cmd', models.CharField(max_length=255)),
                ('run_cmd', models.CharField(max_length=255)),
                ('source_file', models.CharField(max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.TextField()),
                ('compiler_options', models.CharField(blank=True, max_length=100, null=True)),
                ('command_line_arguments', models.CharField(blank=True, max_length=100, null=True)),
                ('stdin', models.TextField(blank=True, null=True)),
                ('expected_output', models.TextField(blank=True, null=True)),
                ('cpu_time_limit', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('cpu_extra_time', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('wall_time_limit', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('memory_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('stack_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('max_processes_and_or_threads', models.PositiveIntegerField(blank=True, null=True)),
                ('enable_per_process_and_thread_time_limit', models.BooleanField(default=False)),
                ('enable_per_process_and_thread_memory_limit', models.BooleanField(default=False)),
                ('max_file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('redirect_stderr_to_stdout', models.BooleanField(default=False)),
                ('enable_network', models.BooleanField(default=False)),
                ('number_of_runs', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('additional_files', models.TextField(blank=True, null=True)),
                ('callback_url', models.TextField(blank=True, max_length=255, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', enumchoicefield.fields.EnumChoiceField(default=submissions.models.Status(1), enum_class=submissions.models.Status, max_length=21)),
                ('stdout', models.TextField(blank=True, null=True)),
                ('time', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('memory', models.PositiveIntegerField(blank=True, null=True)),
                ('stderr', models.TextField(blank=True, null=True)),
                ('compile_output', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('exit_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exit_signal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('wall_time', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queue_host', models.CharField(default=submissions.models.get_hostname, max_length=100)),
                ('execution_host', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='submissions.language')),
            ],
        ),
    ]
