# Generated by Django 4.2 on 2023-04-15 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tasks.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', help_text='A one-line description of the task', max_length=100)),
                ('source', models.TextField()),
                ('html_template', models.TextField(blank=True)),
                ('code', tasks.fields.CodeField(blank=True)),
                ('testcases', tasks.fields.LongJSONField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('disabled', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False, help_text='If checked, this task becomes private to its creator and owner')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tasks', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='Coding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', tasks.fields.CodeField(blank=True)),
                ('testcases', tasks.fields.LongJSONField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='tasks.task')),
            ],
        ),
    ]
