# Generated by Django 4.2 on 2023-04-13 07:35

from django.db import migrations
import tasks.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coding',
            name='testcases',
            field=tasks.fields.LongJSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='code',
            field=tasks.fields.CodeField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='testcases',
            field=tasks.fields.LongJSONField(blank=True, null=True),
        ),
    ]
